module.exports = {
  LOGIN: "LOGIN",
  ADD_POKEMON: "ADD_POKEMON",
  LOADING: "LOADING",
  BATTLE: "BATTLE",
  GET_TRAINER_POKEMONS: "GET_TRAINER_POKEMONS",
  SET_POKEMON_COUNT: "SET_POKEMON_COUNT",
  SET_POKEMONS: "SET_POKEMONS",
};
